;Implement a 32-bit addition. Assume data is present in code memory.	
	AREA  ADDITION_32BIT, CODE, READONLY
    ENTRY

MAIN
    LDR R0,=VALUE1        ;LOAD THE ADDRESS OF FIRST VALUE
    LDR R1,[R0]        ;LOAD THE VALUE TO THE REGISTER
    ADD R0,R0,#0x4        ;ADJUST THE POINTER
    LDR R2,[R0]        ;LOAD THE NEW VALUE
    ADD R1,R1,R2        ;ADD AND STORE THE RESULT IN R1
    LDR R0,=RESULT        ;LOAD THE ADDRESS TO STORE THE VALUE
    LDR R3,[R0]
    STR R1,[R3]        ;STORE THE VALUE
    SWI &11            ;EXIT

VALUE1 DCD &37E3C123        ;SET THE FIRST VALUE
VALUE2 DCD &367402AA        ;SET THE SECOND VALUE
RESULT DCD &40000000            ;ADDRESS USED TO STORE RESULT
    END