;Using subroutine, find the factorial of a number.	
	AREA FACTWITHSBRT, CODE, READONLY
	ENTRY

Main
	MOV R0,#4 ;LOAD THE VALUE TO REGISTER R0
	BL FACT ;BRANCH TO FACT
B1 	B B1 ; CREATING AN INFINITE LOOP

FACT 
	MOV R3,#1 
LOOP 
	CMP R0,#1 
	MULGT R3,R0,R3 ; MULITPLY IF GREATER
	SUBGT R0,R0,#1 ; SUBTRACT IF GREATER
	BGT LOOP ; BRANCH IF GREATER
	MOV PC,R14 ;JUMP BACK TO MAIN FUNCTION
END