;Implement a 16-bit addition. Assume data is present in code memory.	
	AREA ADDITION_16BIT, CODE, READONLY
	ENTRY

MAIN
	LDR R1, VALUE1 ;LOAD THE FIRST NUMBER
	LDR R2, VALUE2 ;LOAD THE SECOND NUMBER
	ADD R1, R1, R2 ;ADD R1 AND R2 AND STORE IN R1 (x = x + y)
	LDR R3, RESULT	;LOAD THE ADDRESS 
	STR R1,[R3] ;STORE THE RESULT
	NOP
VALUE1 DCD &C123 ;FIRST VALUE
	   ALIGN
VALUE2 DCD &02AA ;SECOND VALUE 
	   ALIGN
RESULT DCD &40000000 ;storage for result
	END
