;Find the factorial of a number.
	AREA FACTORIAL, CODE, READONLY
	ENTRY
MAIN
	LDR R0,NUM ;LOAD THE REGISTER WITH THE VALUE
	LDR R1,=#1
FACTORIAL	
	CMP R0,#1 ; CHECK IF R0 IS 1
	BEQ DONE ;BRANCH TO DONE IF EQUAL
	MUL	R2,R1,R0 ;MULTIPLY R1 AND R0 AND STORE RESULT IN R2
	MOV R1,R2 ;MOVE THE VALUE FROM R2 TO R1
	SUB R0,R0,#1 ;SUBTRACT R0 WITH 1 AND STORE IT BACK TO R0
	B FACTORIAL ;KEEP IN LOOP TILL FACTORIAL OF A NUMBER IS FOUND
DONE LDR R4,=RESULT ;LOAD THE ADDRESS
	STR R2,[R4] ;STORE THE RESULT
STOP B STOP ;INFINITE LOOP
NUM DCD 7 ; VALUE TO FIND THE FACTORIAL
	
	AREA OUTPUT, DATA, READWRITE
RESULT DCD 0		;OUTPUT SAVED IN DATA MEMORY
	END