;Find the square root of a number present in 0x40000000.Store the result back in 0x40000030	
	AREA SQUAREOFNUM, CODE, READONLY
	ENTRY

MAIN
	LDR R1, VALUE ;LOAD THE NUMBER
	MOV R1,#5 ;LOAD THE VALUE INTO REGISTER R1
	LDR R3, RESULT ;LOAD THE ADDRESS TO STORE RESULT
	MUL R3,R1,R1 ;FINDING SQUARE OF THE NUMBER (5(DECIMAL)->RESULT(25 IN DECIMAL AND 19 IN HEX))
	NOP
VALUE DCD &40000000 ;ADDRESS OF THE NUMBER 
	   ALIGN
RESULT DCD &40000030 ;ADDRESS TO STORE RESULT
	END
