;Find the length of the string character.
CR EQU 0x0D ;DEFINE CONSTANTS

	AREA LENOFSTRING, CODE, READONLY
	ENTRY

MAIN
	ADR R0, STRING ;LOAD THE ADDRESS OF THE LOOKUP TABLE
	EOR R1, R1, R1 ;CLEAR R1 TO STORE THE COUNT
LOOP
	LDRB R2, [R0], #1 ;LOAD THE FIRST BYTE TO R2
	CMP R2, #CR ;IS IT THE TERMINATOR?
	BEQ DONE ;IF NOT ,THEN CONTINUE LOOP
	ADD R1, R1, #1 ;INCREMENT COUNT
	B LOOP
DONE
	STR R1,CHARCOUNT ;OTHERWISE DONE - STORE RESULT
	NOP

STRING DCB "Hello, World", CR ;ENTER THE STRING TO EVALUTE LENGTH
	  ALIGN
CHARCOUNT DCB 0 ;STORAGE FOR COUNT
		  ALIGN
	END
