;Convert a given number from 0x4000 0000 hex value to ASCII.	
	AREA HEXTOASCII, CODE, READONLY
	ENTRY

MAIN
	LDR R0, DIGIT ;LOAD THE DIGIT
	LDR R1, = RESULT ;LOAD THE ADDRESS FOR THE RESUTL
	MOV R0,#0x06
	CMP R0, #0x0A ;IS THE NUMBER LESS THAN 10 (DECIMAL)
	BLT ADD_0 ;IF YES THEN BRANCH
	ADD R0, R0, #"A"-"0"-0xA ;ADD OFFSET FOR 'A' AND 'F'
ADD_0
	ADD R0, R0, #"0" ;CONVERT TO ASCII
	STR R0, [R1] ;STORE THE RESULT
 
DIGIT DCD &40000000 ; HEX VALUE
RESULT DCD &40000030 ;STORE THE RESULT
	END
